---
- name: Install GNOME
  pacman:
    name:
      - gnome
      - gnome-extra
      - gnome-tweaks
      - xorg-server
      - xorg-xinit
      - xorg-utils
      - xorg-server-utils
    state: present

- include: dconf.yml
- include: gtk.yml
- include: gnome_shell.yml
- include: online_accounts.yml
