---
- name: Upgrade All Packages | System
  pacman: update_cache=yes upgrade=yes
  become: yes


- name: Installation System Utilities
  pacman: name={{item}} state=present
  become: yes
  with_items:
    - htop
    - docker
    - nasm
    - vim
    - cloc
    - openssh
    - tmux
    - wget

- name: Installation Webbrowser
  pacman: name={{item}} state=present
  become: yes
  with_items:
    - firefox
    - firefox-i18n-de
    - chromium
    - flashplugin
    - icedtea-web

- name: Installation Disk Utilities
  pacman: name={{item}} state=present
  become: yes
  with_items:
    - gparted
    - lshw
    - lsof

- name: Installation NodeJs Environment
  pacman: name={{item}} state=present
  become: yes
  with_items:
    - npm
    - nodejs

- name: Installation Latex
  pacman: name={{item}} state=present
  become: yes
  with_items:
    - texlive-most
    - texlive-lang

- name: Installation Alsa
  pacman: name={{item}} state=present
  become: yes
  with_items:
    - alsa-utils
    - alsa-plugins
    - alsa-lib
    - pulseaudio-alsa
    - pavucontrol

- name: Change NPM permission
  command:
    - mkdir ~/.npm-global
    - npm config set prefix '~/.npm-global'
    - echo  export PATH=~/.npm-global/bin:$PATH > ~/.profile
    - source ~/.profile


...
