---
- name: Install Firefox
  pacman:
    name: firefox
    state: present
  tags:
    - firefox

- name: Jail Firefox
  file:
    src: /usr/bin/firejail
    dest: /usr/local/bin/firefox
    state: link
  tags:
    - firefox
    - firejail

- name: Verify Firefox firejail local profile exists
  file:
    path: /etc/firejail/firefox.local
    state: touch
  tags:
    - firefox
    - firejail

- name: Restrict Firefox access to /etc
  lineinfile:
    dest: /etc/firejail/firefox.local
    regexp: "^private-etc"
    line: "private-etc firejail,passwd,group,hostname,hosts,nsswitch.conf,resolv.conf,gtk-2.0,gtk-3.0,fonts,mime.types,asound.conf,pulse,localtime"
  tags:
    - firefox
    - firejail

- name: Install Google Chrome
  aur:
    name: google-chrome-stable
    user: "{{ user.name }}"
    skip_pgp: yes
  tags:
    - chrome

- name: Jail Chrome
  file:
    src: /usr/bin/firejail
    dest: /usr/local/bin/chromium
    state: link
  tags:
    - chrome
    - firejail

- name: Verify Chrome firejail local profile exists
  file:
    path: /etc/firejail/chrome.local
    state: touch
  tags:
    - chrome
    - firejail

- name: Restrict Chrome access to /etc
  lineinfile:
    dest: /etc/firejail/chrome.local
    regexp: "^private-etc"
    line: "private-etc firejail,passwd,group,hostname,hosts,nsswitch.conf,resolv.conf,gtk-2.0,gtk-3.0,fonts,mime.types,asound.conf,pulse,localtime"
  tags:
    - chrome
    - firejail

- name: Install Pepper Flash
  pacman:
    name: pepper-flash
    state: present
  tags:
    - chrome

- name: Install tor-browser
  aur:
    name: tor-browser
    user: "{{ user.name }}"
    skip_pgp: yes
  tags:
    - tor-browser
    - aur

- name: Jail tor-browser
  file:
    src: /usr/bin/firejail
    dest: /usr/local/bin/tor-browser
    state: link
  tags:
    - tor-browser
    - firejail

- name: Push tor-browser firejail profile
  copy:
    src: firejail/tor-browser.profile
    dest: /usr/local/etc/firejail/tor-browser.profile
  notify:
    - activate firejail profiles
  tags:
    - tor-browser
    - firejail

- name: Push rofi browser chooser
  template:
    src: browser.sh.j2
    dest: /usr/local/bin/browser
    mode: 0755
  tags:
    - rofi
    - chooser

- name: Create local desktop application dir
  file:
    path: /usr/local/share/applications
    state: directory
  tags:
    - rofi
    - chooser

- name: Push rofi browser chooser desktop file
  copy:
    src: browser.desktop
    dest: /usr/local/share/applications/browser.desktop
  tags:
    - rofi
    - chooser

- name: Verify mimeapps.list exists
  file:
    path: /etc/xdg/mimeapps.list
    state: touch
  tags:
    - rofi
    - chooser

- name: Set rofi browser chooser as default application for relevant mimetypes
  lineinfile:
    dest: /etc/xdg/mimeapps.list
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: "^text/html=", line: "text/html=browser.desktop" }
    - { regexp: "^text/xml=", line: "text/xml=browser.desktop" }
    - { regexp: "^text/mml=", line: "text/mml=browser.desktop" }
    - {
        regexp: '^application/xhtml\+xml=',
        line: "application/xhtml+xml=browser.desktop",
      }
    - { regexp: "^application/xml=", line: "application/xml=browser.desktop" }
    - {
        regexp: "^x-scheme-handler/http=",
        line: "x-scheme-handler/http=browser.desktop",
      }
    - {
        regexp: "^x-scheme-handler/https=",
        line: "x-scheme-handler/https=browser.desktop",
      }
  tags:
    - rofi
    - chooser
