---
- name: Install GNUradio
  pacman:
    name: gnuradio
    state: present

- name: Install hamlib
  pacman:
    name: hamlib
    state: present

- include: rtl-sdr.yml
- include: radio_mgmt.yml
- include: radio_ops.yml
