---

- name: Installation NPM
  pacman: name=npm state=present
  become: yes

- name: Change NPM permission
  command: {{ item }}
  with_items:
      - mkdir /home/{{user.name}}/.npm-global
      - npm config set prefix '/home/{{user.name}}/.npm-global'

- name: Copy NPM Configuration
  copy: src=profile.j2 dest=/home/{{user.name}}/.profile
  command: source /home/{{user.name}}/.profile


- name: Installation DevTools
  npm: name={{item}} state=present global=yes 
  with_items:
    - bower
    - generator-jhipster
    - gulp
    - grunt-cli
    - yo
