---
  - name: Base 16 -  Checkout Repository
    git: repo=https://github.com/chriskempson/base16-gnome-terminal.git dest=/home/{{ user.name }}/.config/base16-gnome-terminal

  - name: Base16 - copy default-dark
    copy: src=/home/{{user.name}}/.config/base16-gnome-terminal/base16-default.dark.sh
          dest=/home/{{user.name}}/base16-default.dark.sh
          mode=0755

  - name: Base16 - install default dark
    shell: base16-default.dark.sh

  - name: base16 - set system font to source code pro
    gconftool-2:
      key: /apps/gnome-terminal/profiles/base-16-default-dark/font
      string: "Monaco Bold 11"

  - name: base16 - dont use default system font in terminal
    gconftool-2:
      key: /apps/gnome-terminal/profiles/base-16-default-dark/use_system_font
      bool: false

  - name: base16 - set default terminal profile
    gconftool-2:
      key: /apps/gnome-terminal/global/default_profile
      string: "base-16-default-dark"

  - name: base-16 - get base16-shell so that colors show up correctly in vim
    git: repo=https://github.com/chriskempson/base16-shell.git  dest=/home/{{user.name}}/.config/base16-shell"
