---
  - name: Base 16 -  Checkout Repository
    git: repo=https://github.com/aaron-williamson/base16-gnome-terminal.git dest=/home/{{ username }}/.config/base16-gnome-terminal

  - name: Base16 - install default dark
    shell: /home/{{username}}/.config/base16-gnome-terminal/color-scripts/base16-default-dark.sh
