---
  - name: Installation fish shell
    pacman: name=fish state=present
    become: yes

  - name: Set fish shell as default shell
    command: chsh -s /usr/bin/fish
    become: yes

  - name: Set Configuration
    template: src=config.j2 dest=/home/{{username}}/.config/fish/config.fish

  - name: Copy functions
    copy: src={{ item }}.j2 dest=/home/{{username}}/.config/fish/functions/{{ item }}.fish
    with_items:
      - reload
      - sudo !!
      - fish_prompt
