---
- name: Set Configuration
  template:
    src: config.j2
    dest: /home/{{ user.name }}/.config/fish/config.fish

- name: use oh-my-fish
  shell: |
    curl -L https://get.oh-my.fish | fish

- name: Copy fish helper
  template:
    src: "{{ item }}.j2"
    dest: /home/{{ user.name }}/.config/fish/{{ item }}
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
  with_items:
    - aliases.fish

- name: Copy functions
  copy:
    src: "{{ item }}.j2"
    dest: /home/{{ user.name }}/.config/fish/functions/{{ item }}.fish
  with_items:
    - reload

- name: Install pure theme
  shell: |
    omf install pure
    ln -s $OMF_PATH/themes/pure/conf.d/pure.fish ~/.config/fish/conf.d/pure.fish
    ln -s $OMF_PATH/themes/pure/conf.d/_pure_init.fish ~/.config/fish/conf.d/pure_init.fish
